export type PlayerStatsListRow = {
  player_slug: string;
  opta_player_id: string | null;
  player_name: string;
  full_name: string | null;
  team_slug: string | null;
  team_name: string | null;
  position_code: string;
  position_group: string;
  age: number | null;
  shirt_number: number | null;
  nationality: string | null;
  photo_url: string | null;
  in_current_squad: boolean;
  has_stats: boolean;
  appearances: number;
  starts: number;
  goals: number;
  assists: number;
  total_minutes: number;
  avg_minutes: number | null;
  market_value_eur: number | null;
  xg: number | null;
  xgot: number | null;
  xa: number | null;
  yellowCards: number | null;
  redCards: number | null;
};

export type TslAdvancedRow = {
  season_label: string;
  opta_player_id: string;
  appearances: number | null;
  minutes: number | null;
  xgot: number | null;
  xa: number | null;
  key_passes: number | null;
  long_balls: number | null;
  accurate_long_balls: number | null;
  duels_won: number | null;
  duels_lost: number | null;
  aerials_won: number | null;
  aerials_lost: number | null;
  dribbles_won: number | null;
  dribbles_attempted: number | null;
  clearances: number | null;
  ball_recoveries: number | null;
  big_chances_created: number | null;
  big_chances_missed: number | null;
  errors_leading_to_shot: number | null;
  errors_leading_to_goal: number | null;
  km_covered: number | null;
  sprints: number | null;
  top_speed: number | null;
  carry_distance_m: number | null;
  progressive_carry_distance_m: number | null;
};
