-- 2026-10-01: GSheet sekmesi milli takim sayfasinda da (sahip istegi).
-- msm_gsheet_v1 milli maclari artik DISLAMAZ; league='trnat' olarak verir
-- (ref.national_competitions). tsl / tff1 satirlari degismedi (md5 birebir).
-- Kupa (CL/EL/Konf) dislamasi aynen duruyor. URETILMIS dosya (canli viewdef).

CREATE OR REPLACE VIEW analytics.msm_gsheet_v1 AS
 WITH mt AS (
         SELECT match_team_stats.id,
            match_team_stats.source,
            match_team_stats.source_match_id,
            match_team_stats.source_team_id,
            match_team_stats.team_name,
            match_team_stats.team_side,
            match_team_stats.opponent_team_source_id,
            match_team_stats.opponent_team_name,
            match_team_stats.competition,
            match_team_stats.match_datetime,
            match_team_stats.match_date_text,
            match_team_stats.score_for,
            match_team_stats.score_against,
            match_team_stats.result_code,
            match_team_stats.summary_goals,
            match_team_stats.summary_assists,
            match_team_stats.summary_red_cards,
            match_team_stats.summary_yellow_cards,
            match_team_stats.summary_corners_won,
            match_team_stats.summary_shots,
            match_team_stats.summary_shots_on_target,
            match_team_stats.summary_blocked_shots,
            match_team_stats.summary_passes,
            match_team_stats.summary_crosses,
            match_team_stats.summary_tackles,
            match_team_stats.summary_offsides,
            match_team_stats.summary_fouls_conceded,
            match_team_stats.summary_fouls_won,
            match_team_stats.summary_saves,
            match_team_stats.details_accurate_pass,
            match_team_stats.details_hit_woodwork,
            match_team_stats.details_attempts_ibox,
            match_team_stats.details_attempts_obox,
            match_team_stats.details_headed_shots,
            match_team_stats.details_expected_goals,
            match_team_stats.details_goal_kicks,
            match_team_stats.details_total_throws,
            match_team_stats.details_out_of_box_goals,
            match_team_stats.details_right_foot_goals,
            match_team_stats.details_left_foot_goals,
            match_team_stats.details_headed_goals,
            match_team_stats.details_penalty_goals,
            match_team_stats.details_freekick_goals,
            match_team_stats.details_fantasy_assist,
            match_team_stats.opta_player_count,
            match_team_stats.opta_starter_count,
            match_team_stats.opta_substitute_count,
            match_team_stats.opta_points_total,
            match_team_stats.opta_minutes_total,
            match_team_stats.opta_goals_total,
            match_team_stats.opta_shots_on_target_total,
            match_team_stats.opta_shots_off_target_total,
            match_team_stats.opta_shots_blocked_total,
            match_team_stats.opta_own_goals_total,
            match_team_stats.opta_assists_total,
            match_team_stats.opta_passes_total,
            match_team_stats.opta_crosses_total,
            match_team_stats.opta_tackles_total,
            match_team_stats.opta_interceptions_total,
            match_team_stats.opta_fouls_won_total,
            match_team_stats.opta_fouls_conceded_total,
            match_team_stats.opta_offsides_total,
            match_team_stats.opta_cards_yellow_total,
            match_team_stats.opta_cards_red_total,
            match_team_stats.opta_goals_conceded_total,
            match_team_stats.opta_penalties_won_total,
            match_team_stats.opta_saves_total,
            match_team_stats.opta_penalties_saved_total,
            match_team_stats.raw_summary_totals,
            match_team_stats.raw_details_totals,
            match_team_stats.raw_opta_totals,
            match_team_stats.payload_last_seen_at,
            match_team_stats.created_at,
            match_team_stats.updated_at,
            match_team_stats.sofascore_extras
           FROM football.match_team_stats
          WHERE match_team_stats.source = 'sofascore'::text AND (match_team_stats.competition IS NULL OR (match_team_stats.competition <> ALL (ARRAY['UEFA Şampiyonlar Ligi'::text, 'UEFA Avrupa Ligi'::text, 'UEFA Konferans Ligi'::text])))
        )
 SELECT h.source_match_id,
        CASE
            WHEN h.competition = 'Süper Lig'::text THEN 'tsl'::text
            WHEN h.competition = 'Trendyol 1. Lig'::text THEN 'tff1'::text
            WHEN (EXISTS ( SELECT 1 FROM ref.national_competitions nc WHERE nc.competition = h.competition)) THEN 'trnat'::text
            ELSE h.competition
        END AS league,
    h.competition,
    h.match_datetime,
        CASE
            WHEN EXTRACT(month FROM h.match_datetime) >= 7::numeric THEN (EXTRACT(year FROM h.match_datetime)::integer || '/'::text) || (EXTRACT(year FROM h.match_datetime)::integer + 1)
            ELSE ((EXTRACT(year FROM h.match_datetime)::integer - 1) || '/'::text) || EXTRACT(year FROM h.match_datetime)::integer
        END AS season_label,
    h.source_team_id AS home_team_id,
    h.team_name AS home_team_name,
    a.source_team_id AS away_team_id,
    a.team_name AS away_team_name,
    h.score_for AS ft_home,
    a.score_for AS ft_away,
    (h.sofascore_extras ->> 'added_time_1h'::text)::integer AS added_time_1h,
    (h.sofascore_extras ->> 'added_time_2h'::text)::integer AS added_time_2h,
    (h.sofascore_extras ->> 'card_total'::text)::integer AS card_home,
    (a.sofascore_extras ->> 'card_total'::text)::integer AS card_away,
    h.summary_corners_won AS corner_home,
    a.summary_corners_won AS corner_away,
    h.summary_shots AS shot_home,
    a.summary_shots AS shot_away,
    h.summary_shots_on_target AS sot_home,
    a.summary_shots_on_target AS sot_away,
    h.summary_fouls_conceded AS foul_home,
    a.summary_fouls_conceded AS foul_away,
    h.summary_offsides AS offside_home,
    a.summary_offsides AS offside_away,
    h.summary_saves AS saves_home,
    a.summary_saves AS saves_away,
    h.details_total_throws AS throwin_home,
    a.details_total_throws AS throwin_away,
    h.summary_tackles AS tackle_home,
    a.summary_tackles AS tackle_away,
    h.details_goal_kicks AS goalkick_home,
    a.details_goal_kicks AS goalkick_away,
    (h.sofascore_extras ->> 'possession_pct'::text)::numeric AS possession_home,
    (a.sofascore_extras ->> 'possession_pct'::text)::numeric AS possession_away,
    COALESCE(h.summary_red_cards, 0) + COALESCE(a.summary_red_cards, 0) AS rc_total,
    COALESCE((h.sofascore_extras ->> 'var_count'::text)::integer, 0) + COALESCE((a.sofascore_extras ->> 'var_count'::text)::integer, 0) AS var_total,
    COALESCE((h.sofascore_extras ->> 'penalties'::text)::integer, 0) + COALESCE((a.sofascore_extras ->> 'penalties'::text)::integer, 0) AS pen_total,
    COALESCE(h.details_hit_woodwork, 0) + COALESCE(a.details_hit_woodwork, 0) AS woodwork_total,
    COALESCE((h.sofascore_extras ->> 'own_goals'::text)::integer, 0) + COALESCE((a.sofascore_extras ->> 'own_goals'::text)::integer, 0) AS owngoal_total,
    tmh.team_slug AS home_team_slug,
    tma.team_slug AS away_team_slug
   FROM mt h
     JOIN mt a ON a.source_match_id = h.source_match_id AND h.team_side = 'home'::text AND a.team_side = 'away'::text
     LEFT JOIN ref.team_mapping tmh ON tmh.source_team_id = h.source_team_id
     LEFT JOIN ref.team_mapping tma ON tma.source_team_id = a.source_team_id;

notify pgrst, 'reload schema';
